---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: ubuntu-12.04-cloudimg
    box_url: http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: 10.24.4

suites:
- name: rsyslog
  run_list: ["recipe[rsyslog::server]", "recipe[rsyslog::client]"]
  attributes:
    rsyslog:
      server_ip: 127.0.0.1
- name: rsyslog-clientdisabled
  run_list: ["recipe[rsyslog::clientdisabled]"]
  attributes:
